### ISSUE TITLE
Use RM08 when Askim disconnects does not follow any setpoints

### ISSUE THREAD

**Issue by nathantim** [project-march/somanet-ethercat-drive#5]
On joint

**Comment by phil-due** [comment]
On dev branch the Transmission factor causes the problem. This leads to way to high set points and the somenat does not accept them anymore. I created a new branch for this "fix_aksim_error_handling". The problem seems that either the scaling/offset calculation goes wrong. Thus the new position limits/ the set point are wrong. This means also the soft stops don't work properly anymore so be aware of that if you make tests.

**Comment by phil-due** [comment]
The scaling seems to work now, however there is a problem with the rm08 multiturn position. A reason could be that it is an integer so it can capture only 2^32 ticks while we actually need 2^12(rm08 ticks)*100(transmission)*2^16(Aksim ticks)=26843545600. I tried to change it to long long but there seems to be an other error. At certain positions the rm08 jumps between two positions a negative and a positive one.

**Comment by phil-due** [comment]
Problem was a wrong calculation of the multiturn position of the ssi sensor. Fixed with commit 20cc28a4fa and https://github.com/project-march/somanet-motorcontrol/commit/f3b48ab7e5182ec0dbc89b7f82cc34f96c4b04b3
